module pcre_constants
  use, intrinsic :: iso_c_binding, only : c_int
  implicit none

  ! Extension
  integer(c_int), parameter :: PCRE_SUCCESS                = 0
    !! The code ran successfully
  integer(c_int), parameter :: PCRE_ERROR_NOMATCH          = -1
    !! The subject string did not match the pattern.
  integer(c_int), parameter :: PCRE_ERROR_NULL             = -2
    !! Either code or subject was passed as NULL, or ovector was NULL and ovecsize was not zero.
  integer(c_int), parameter :: PCRE_ERROR_BADOPTION        = -3
    !! An unrecognized bit was set in the options argument.
  integer(c_int), parameter :: PCRE_ERROR_BADMAGIC         = -4
    !! PCRE stores a 4-byte "magic number" at the start of the compiled code, to catch the case when it is passed a junk pointer and to detect when a pattern that was compiled in an environment of one endianness is run in an environment with the other endianness. This is the error that PCRE gives when the magic number is not present.
  integer(c_int), parameter :: PCRE_ERROR_UNKNOWN_OPCODE   = -5
    !! While running the pattern match, an unknown item was encountered in the compiled pattern. This error could be caused by a bug in PCRE or by overwriting of the compiled pattern.
  integer(c_int), parameter :: PCRE_ERROR_NOMEMORY         = -6
    !! If a pattern contains back references, but the ovector that is passed to pcre_exec() is not big enough to remember the referenced substrings, PCRE gets a block of memory at the start of matching to use for this purpose. If the call via pcre_malloc() fails, this error is given. The memory is automatically freed at the end of matching.
    !! This error is also given if pcre_stack_malloc() fails in pcre_exec(). This can happen only when PCRE has been compiled with --disable-stack-for-recursion.
  integer(c_int), parameter ::  PCRE_ERROR_NOSUBSTRING     = -7
    !! This error is used by the pcre_copy_substring(), pcre_get_substring(), and pcre_get_substring_list() functions (see below). It is never returned by pcre_exec().
  integer(c_int), parameter :: PCRE_ERROR_MATCHLIMIT        = -8
    !! The backtracking limit, as specified by the match_limit field in a pcre_extra structure (or defaulted) was reached. See the description above.
  integer(c_int), parameter :: PCRE_ERROR_CALLOUT          = -9
    !! This error is never generated by pcre_exec() itself. It is provided for use by callout functions that want to yield a distinctive error code. See the pcrecallout documentation for details.
  integer(c_int), parameter :: PCRE_ERROR_BADUTF8          = -10
    !! A string that contains an invalid UTF-8 byte sequence was passed as a subject, and the PCRE_NO_UTF8_CHECK option was not set. If the size of the output vector (ovecsize) is at least 2, the byte offset to the start of the the invalid UTF-8 character is placed in the first element, and a reason code is placed in the second element. The reason codes are listed in the following section. For backward compatibility, if PCRE_PARTIAL_HARD is set and the problem is a truncated UTF-8 character at the end of the subject (reason codes 1 to 5), PCRE_ERROR_SHORTUTF8 is returned instead of PCRE_ERROR_BADUTF8.
  integer(c_int), parameter :: PCRE_ERROR_BADUTF8_OFFSET = -11
    !! The UTF-8 byte sequence that was passed as a subject was checked and found to be valid (the PCRE_NO_UTF8_CHECK option was not set), but the value of startoffset did not point to the beginning of a UTF-8 character or the end of the subject.
  integer(c_int), parameter :: PCRE_ERROR_PARTIAL        = -12
    !! The subject string did not match, but it did match partially. See the pcrepartial documentation for details of partial matching.
  integer(c_int), parameter :: PCRE_ERROR_BADPARTIAL     = -13
    !! This code is no longer in use. It was formerly returned when the PCRE_PARTIAL option was used with a compiled pattern containing items that were not supported for partial matching. From release 8.00 onwards, there are no restrictions on partial matching.
  integer(c_int), parameter :: PCRE_ERROR_INTERNAL       = -14
    !! An unexpected internal error has occurred. This error could be caused by a bug in PCRE or by overwriting of the compiled pattern.
  integer(c_int), parameter :: PCRE_ERROR_BADCOUNT       = -15
    !! This error is given if the value of the ovecsize argument is negative.
  integer(c_int), parameter :: PCRE_ERROR_RECURSIONLIMIT = -21
    !! The internal recursion limit, as specified by the match_limit_recursion field in a pcre_extra structure (or defaulted) was reached. See the description above.
  integer(c_int), parameter :: PCRE_ERROR_BADNEWLINE     = -23
    !! An invalid combination of PCRE_NEWLINE_xxx options was given.
  integer(c_int), parameter :: PCRE_ERROR_BADOFFSET      = -24
    !! The value of startoffset was negative or greater than the length of the subject, that is, the value in length.
  integer(c_int), parameter :: PCRE_ERROR_SHORTUTF8      = -25
    !! This error is returned instead of PCRE_ERROR_BADUTF8 when the subject string ends with a truncated UTF-8 character and the PCRE_PARTIAL_HARD option is set. Information about the failure is returned as for PCRE_ERROR_BADUTF8. It is in fact sufficient to detect this case, but this special error code for PCRE_PARTIAL_HARD precedes the implementation of returned information; it is retained for backwards compatibility.
  integer(c_int), parameter :: PCRE_ERROR_RECURSELOOP    = -26
    !! This error is returned when pcre_exec() detects a recursion loop within the pattern. Specifically, it means that either the whole pattern or a subpattern has been called recursively for the second time at the same position in the subject string. Some simple patterns that might do this are detected and faulted at compile time, but more complicated cases, in particular mutual recursions between two different subpatterns, cannot be detected until run time.
  integer(c_int), parameter :: PCRE_ERROR_JIT_STACKLIMIT = -27
    !! This error is returned when a pattern that was successfully studied using a JIT compile option is being matched, but the memory available for the just-in-time processing stack is not large enough. See the pcrejit documentation for more details.
  integer(c_int), parameter :: PCRE_ERROR_BADMODE        = -28
    !! This error is given if a pattern that was compiled by the 8-bit library is passed to a 16-bit or 32-bit library function, or vice versa.
  integer(c_int), parameter :: PCRE_ERROR_BADENDIANNESS  = -29
    !! This error is given if a pattern that was compiled and saved is reloaded on a host with different endianness. The utility function pcre_pattern_to_host_byte_order() can be used to convert such a pattern so that it runs on the new host.
  integer(c_int), parameter :: PCRE_ERROR_JIT_BADOPTION  = -31
    !! This error is returned when a pattern that was successfully studied using a JIT compile option is being matched, but the matching mode (partial or complete match) does not correspond to any JIT compilation mode. When the JIT fast path function is used, this error may be also given for invalid options. See the pcrejit documentation for more details.
  integer(c_int), parameter :: PCRE_ERROR_BADLENGTH      = -32
    !! This error is given if pcre_exec() is called with a negative value for the length argument.
  integer(c_int), parameter :: PCRE_ERROR_UNSET          = -33
    !! The requested field by pcre_fullinfo() is not set


  ! Request types for pcre_fullinfo
  integer(c_int), parameter :: PCRE_INFO_OPTIONS             = 0
  integer(c_int), parameter :: PCRE_INFO_SIZE                = 1
  integer(c_int), parameter :: PCRE_INFO_CAPTURECOUNT        = 2
  integer(c_int), parameter :: PCRE_INFO_BACKREFMAX          = 3
  integer(c_int), parameter :: PCRE_INFO_FIRSTBYTE           = 4
  integer(c_int), parameter :: PCRE_INFO_FIRSTTABLE          = 5
  integer(c_int), parameter :: PCRE_INFO_LASTLITERAL         = 6
  integer(c_int), parameter :: PCRE_INFO_NAMEENTRYSIZE       = 7
  integer(c_int), parameter :: PCRE_INFO_NAMECOUNT           = 8
  integer(c_int), parameter :: PCRE_INFO_NAMETABLE           = 9
  integer(c_int), parameter :: PCRE_INFO_STUDYSIZE           = 10
  integer(c_int), parameter :: PCRE_INFO_DEFAULT_TABLES      = 11
  integer(c_int), parameter :: PCRE_INFO_OKPARTIAL           = 12
  integer(c_int), parameter :: PCRE_INFO_JCHANGED            = 13
  integer(c_int), parameter :: PCRE_INFO_HASCRORLF           = 14
  integer(c_int), parameter :: PCRE_INFO_MINLENGTH           = 15
  integer(c_int), parameter :: PCRE_INFO_JIT                 = 16
  integer(c_int), parameter :: PCRE_INFO_JITSIZE             = 17
  integer(c_int), parameter :: PCRE_INFO_MAXLOOKBEHIND       = 18
  integer(c_int), parameter :: PCRE_INFO_FIRSTCHARACTER      = 19
  integer(c_int), parameter :: PCRE_INFO_FIRSTCHARACTERFLAGS = 20
  integer(c_int), parameter :: PCRE_INFO_REQUIREDCHAR        = 21
  integer(c_int), parameter :: PCRE_INFO_REQUIREDCHARFLAGS   = 22
  integer(c_int), parameter :: PCRE_INFO_MATCHLIMIT          = 23
  integer(c_int), parameter :: PCRE_INFO_RECURSIONLIMIT      = 24
  integer(c_int), parameter :: PCRE_INFO_MATCH_EMPTY         = 25

  ! Public options
  integer(c_int), parameter :: PCRE_CASELESS          = int(z'00000001')
  integer(c_int), parameter :: PCRE_MULTILINE         = int(z'00000002')
  integer(c_int), parameter :: PCRE_DOTALL            = int(z'00000004')
  integer(c_int), parameter :: PCRE_EXTENDED          = int(z'00000008')
  integer(c_int), parameter :: PCRE_ANCHORED          = int(z'00000010')
  integer(c_int), parameter :: PCRE_DOLLAR_ENDONLY    = int(z'00000020')
  integer(c_int), parameter :: PCRE_EXTRA             = int(z'00000040')
  integer(c_int), parameter :: PCRE_NOTBOL            = int(z'00000080')
  integer(c_int), parameter :: PCRE_NOTEOL            = int(z'00000100')
  integer(c_int), parameter :: PCRE_UNGREEDY          = int(z'00000200')
  integer(c_int), parameter :: PCRE_NOTEMPTY          = int(z'00000400')
  integer(c_int), parameter :: PCRE_UTF8              = int(z'00000800')
  integer(c_int), parameter :: PCRE_UTF16             = int(z'00000800')
  integer(c_int), parameter :: PCRE_UTF32             = int(z'00000800')
  integer(c_int), parameter :: PCRE_NO_AUTO_CAPTURE   = int(z'00001000')
  integer(c_int), parameter :: PCRE_NO_UTF8_CHECK     = int(z'00002000')
  integer(c_int), parameter :: PCRE_NO_UTF16_CHECK    = int(z'00002000')
  integer(c_int), parameter :: PCRE_NO_UTF32_CHECK    = int(z'00002000')
  integer(c_int), parameter :: PCRE_AUTO_CALLOUT      = int(z'00004000')
  integer(c_int), parameter :: PCRE_PARTIAL_SOFT      = int(z'00008000')
  integer(c_int), parameter :: PCRE_PARTIAL           = int(z'00008000')

  integer(c_int), parameter :: PCRE_NEVER_UTF         = int(z'00010000')
  integer(c_int), parameter :: PCRE_DFA_SHORTEST      = int(z'00010000')

  integer(c_int), parameter :: PCRE_NO_AUTO_POSSESS   = int(z'00020000')
  integer(c_int), parameter :: PCRE_DFA_RESTART       = int(z'00020000')

  integer(c_int), parameter :: PCRE_FIRSTLINE         = int(z'00040000')
  integer(c_int), parameter :: PCRE_DUPNAMES          = int(z'00080000')
  integer(c_int), parameter :: PCRE_NEWLINE_CR        = int(z'00100000')
  integer(c_int), parameter :: PCRE_NEWLINE_LF        = int(z'00200000')
  integer(c_int), parameter :: PCRE_NEWLINE_CRLF      = int(z'00300000')
  integer(c_int), parameter :: PCRE_NEWLINE_ANY       = int(z'00400000')
  integer(c_int), parameter :: PCRE_NEWLINE_ANYCRLF   = int(z'00500000')
  integer(c_int), parameter :: PCRE_BSR_ANYCRLF       = int(z'00800000')
  integer(c_int), parameter :: PCRE_BSR_UNICODE       = int(z'01000000')
  integer(c_int), parameter :: PCRE_JAVASCRIPT_COMPAT = int(z'02000000')
  integer(c_int), parameter :: PCRE_NO_START_OPTIMIZE = int(z'04000000')
  integer(c_int), parameter :: PCRE_NO_START_OPTIMISE = int(z'04000000')
  integer(c_int), parameter :: PCRE_PARTIAL_HARD      = int(z'08000000')
  integer(c_int), parameter :: PCRE_NOTEMPTY_ATSTART  = int(z'10000000')
  integer(c_int), parameter :: PCRE_UCP               = int(z'20000000')

  integer(c_int), parameter :: PCRE_CONFIG_UTF8                   =  0
  integer(c_int), parameter :: PCRE_CONFIG_NEWLINE                =  1
  integer(c_int), parameter :: PCRE_CONFIG_LINK_SIZE              =  2
  integer(c_int), parameter :: PCRE_CONFIG_POSIX_MALLOC_THRESHOLD =  3
  integer(c_int), parameter :: PCRE_CONFIG_MATCH_LIMIT            =  4
  integer(c_int), parameter :: PCRE_CONFIG_STACKRECURSE           =  5
  integer(c_int), parameter :: PCRE_CONFIG_UNICODE_PROPERTIES     =  6
  integer(c_int), parameter :: PCRE_CONFIG_MATCH_LIMIT_RECURSION  =  7
  integer(c_int), parameter :: PCRE_CONFIG_BSR                    =  8
  integer(c_int), parameter :: PCRE_CONFIG_JIT                    =  9
  integer(c_int), parameter :: PCRE_CONFIG_UTF16                  = 10
  integer(c_int), parameter :: PCRE_CONFIG_JITTARGET              = 11
  integer(c_int), parameter :: PCRE_CONFIG_UTF32                  = 12
  integer(c_int), parameter :: PCRE_CONFIG_PARENS_LIMIT           = 13

end module pcre_constants
